### ISSUE TITLE
Issue with Kylin Integration with superset 

### ISSUE THREAD

**Issue by vatsalpande** [Kyligence/kylinpy#15]
am trying to configure Kylin connection with Superset. I have configured kylin package and my connection seems to be ok. However, it doesn't show me any tables, at the bottom of the page.
I checked the logs and it tries to call the below Rest API -
############################################################################
method: GET
url: http://XXXX.XXXX:80/kylin/api/tables_and_columns?project=projectName
headers: {'User-Agent': 'Kylin Python Client', 'Authorization': 'Basic someEncodedPassword'}
body: None
############################################################################
I have tried the above url with Postman, and it returns me table and column names.

Moreover, if I go to Sql Editor in Sql Lab it shows me Database name, schema & Tables. But as soon as I click on any of the table, it gives an error " startswith first arg must be bytes or a tuple of bytes, not str"

Attached screenshots for same
<img width="1423" alt="3" src="https://user-images.githubusercontent.com/12035570/46064492-63abff80-c124-11e8-9266-584043d7b884.png">
<img width="1421" alt="1" src="https://user-images.githubusercontent.com/12035570/46064494-63abff80-c124-11e8-8549-ea267768a2c3.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/12035570/46064495-63abff80-c124-11e8-956b-d4578ecbf715.png">

Not sure, if its related to kylin package or with Superset. Any suggestions will be appreciated

**Comment by zhaoyongjie** [comment]
@vatsalpande Thank you for you feedback, this issue is fixed by kylinpy v1.6.2.
