### ISSUE TITLE
The result set size is default to 50000 and can not be changed.

### ISSUE THREAD

**Issue by tosakyo** [Kyligence/kylinpy#18]
The 'execute' method of the 'Cursor' class passes only query but not params to the 'query' method of the 'Project' class. The query method set 'limit' default to 50000. The result set size will be less than or equal to 50000. This is not we want when the result set size is larger than 50000.

![image](https://user-images.githubusercontent.com/35860842/54172880-9707fe00-44ba-11e9-8d9b-d6d2226e021a.png)

![image](https://user-images.githubusercontent.com/35860842/54172983-0120a300-44bb-11e9-8cd9-793d10553ad4.png)

**Comment by zhaoyongjie** [comment]
@tosakyo For Kylin, it is generally used to aggregate queries, and is not suitable for detailed queries. It is recommended that you add filter. 

Future versions will expose query limit configuration items.
