### ISSUE TITLE
kylinpy.errors.KylinError or kylinpy.exceptions.KylinError?

### ISSUE THREAD

**Issue by tosakyo** [Kyligence/kylinpy#19]
After installation with `pip install --upgrade kylinpy`, I can import KylinError like this:
`from kylinpy.errors import KylinError`
However, if install kylinpy from the code with `python setup.py install`, Import Error will be thrown, unless I change this to `from kylinpy.exceptions import KylinError`:
![image](https://user-images.githubusercontent.com/35860842/54339073-b8115000-466e-11e9-9376-89e2772e76d1.png)

**Comment by zhaoyongjie** [comment]
@tosakyo you can use workaround: pip install -e .

I will fix this for fit setup.py
