### ISSUE TITLE
got kylinpy.exceptions.KylinQueryError when use Query.first or Query.filter

### ISSUE THREAD

**Issue by px4860** [Kyligence/kylinpy#24]
First i got an engine and a session form kylin and create table like this `class Date(Base):
    __table__ = Table('DIM_DATE', metadata, schema='WEB_AD', autoload=True)
    __mapper_args__ = {
        'primary_key': [Table('DIM_DATE', metadata, schema='WEB_AD', autoload=True).c.DATE_KEY]
    }`.When i start a query from this table if i use operator like first() or filter(), i got an error like this `kylinpy.exceptions.KylinQueryError: Encountered "= %" at line 3, column 38. Was expecting one of:     <EOF>      "ORDER" ...     "LIMIT" ...     "OFFSET" ...     "FETCH" ...     "GROUP" ..`.
There are some code i used `result = session.query(Date.YEAR,Date.MONTH).filter(Date.DATE_KEY == 20161231).first()`

**Comment by zhaoyongjie** [comment]
sorry, this is a bug, I can fix it soon.
