### ISSUE TITLE
When I use the 'case when' in select, it returns an extra space

### ISSUE THREAD

**Issue by liufengchaoaa** [Kyligence/kylinpy#25]
like this "SELECT CASE WHEN org=1 THEN 'SAB' ELSE 'CD' END AS SCALE, from_date FROM xx GROUP BY from_date , CASE WHEN org=1 THEN 'SAB' ELSE 'CD' END" 
i hope the result is "CD" or "SAB", but it returns "CD " or  "SAB"

**Comment by zhaoyongjie** [comment]
where * extra space * is ?

**Comment by liufengchaoaa** [comment]
> where * extra space * is ?

l hope "CD",but return "CD ",behind "CD*"
"SAB" is normal，only "CD ", the sort selection
