### ISSUE TITLE
Kylinpy can't work 

### ISSUE THREAD

**Issue by sunlc210** [Kyligence/kylinpy#42]
after type  "pip install --upgrade kylinpy",the CRT display 

root@dp-kf-graphdb-2:~/kylinpy#  pip install --upgrade kylinpy
Downloading/unpacking kylinpy from https://files.pythonhosted.org/packages/68/16/343f8e07f89b21967f1b2afada8f106e4faa0602226e1aeac6faee28f276/kylinpy-2.8.3.tar.gz#sha256=fda35dbbc2ac4e26ae02e5566a39684b05827a666c83613c58da384f7ed06024
  Downloading kylinpy-2.8.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/kylinpy/setup.py) egg_info for package kylinpy
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    
    warning: manifest_maker: MANIFEST.in, line 2: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
    
Installing collected packages: kylinpy
  Found existing installation: kylinpy 0.0.999dev
    Can't uninstall 'kylinpy'. No files were found to uninstall.
  Running setup.py install for kylinpy
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    
    warning: manifest_maker: MANIFEST.in, line 2: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...
    
Successfully installed kylinpy
Cleaning up...

means install successful ,but type the command  "kylinpy", 

error display 
:root@dp-kf-graphdb-2:~/kylinpy# kylinpy
kylinpy: command not found

no idea the reason ,the document dosen't show more infro to debug

**Comment by zhaoyongjie** [comment]
1. It seems like that you have been install dev version of kylinpy, please try this command:
```
pip install --no-cache-dir --upgrade kylinpy
```

2. I am sorry say that Kylinpy no longer provides CLI tools(command line utilities), so you can't use kylinpy in Shell
