### ISSUE TITLE
Incorrect statement try to convert kylin return boolean to sql boolean

### ISSUE THREAD

**Issue by lexrf** [Kyligence/kylinpy#5]
Kylin return boolean as string "true" and "false". Kylinpy try to use dict to covert it to python bool value.

the dict can be found in utils/kylin_types.py line 21

...
    BOOLEAN=bool,
...

in line 31, this map will cause follow action

bool_value = bool(str)

However, this won't work, in python, bool("true") is True, bool("false") is True still.

I have change line 21 in my private kylinpy like this:

    BOOLEAN=lambda x: x in ["True","true","TRUE"],

It works.

But I'm sure we need consider a better solution later.

**Comment by zhaoyongjie** [comment]
Thanks for you report, I have fixed this issue for boolean convert.
